// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsNow.Models;

namespace NewsNow.Migrations
{
    [DbContext(typeof(NewsNowContext))]
    [Migration("20180919180419_Initiat-Data11")]
    partial class InitiatData11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NewsNow.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<string>("DetailedContent");

                    b.Property<string>("DetailedHeader");

                    b.Property<string>("HomeContent");

                    b.Property<string>("HomeHeader");

                    b.Property<string>("HomeImage");

                    b.HasKey("ArticleId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new { ArticleId = 1, CategoryId = 1, DateCreated = new DateTime(2018, 9, 19, 21, 4, 19, 254, DateTimeKind.Local), HomeContent = "This is the description of an article. Read more.", HomeHeader = "Targets in Syria: Bombs" },
                        new { ArticleId = 2, CategoryId = 1, DateCreated = new DateTime(2018, 9, 19, 21, 4, 19, 256, DateTimeKind.Local), HomeContent = "This is the description of an article. Read more.", HomeHeader = "\"West side is a prison\"" },
                        new { ArticleId = 3, CategoryId = 1, DateCreated = new DateTime(2018, 9, 19, 21, 4, 19, 256, DateTimeKind.Local), HomeContent = "This is the description of an article. Read more.", HomeHeader = "The Israeli startups in space" },
                        new { ArticleId = 4, CategoryId = 2, DateCreated = new DateTime(2018, 9, 19, 21, 4, 19, 256, DateTimeKind.Local), HomeContent = "This is the description of an article. Read more.", HomeHeader = "1:0 on Raanana vs Kaka" },
                        new { ArticleId = 5, CategoryId = 2, DateCreated = new DateTime(2018, 9, 19, 21, 4, 19, 256, DateTimeKind.Local), HomeContent = "This is the description of an article. Read more.", HomeHeader = "Dummy article" },
                        new { ArticleId = 6, CategoryId = 2, DateCreated = new DateTime(2018, 9, 19, 21, 4, 19, 256, DateTimeKind.Local), HomeContent = "This is the description of an article. Read more.", HomeHeader = "Dummy article" },
                        new { ArticleId = 7, CategoryId = 3, DateCreated = new DateTime(2018, 9, 19, 21, 4, 19, 256, DateTimeKind.Local), HomeContent = "This is the description of an article. Read more.", HomeHeader = "Dummy article" },
                        new { ArticleId = 8, CategoryId = 3, DateCreated = new DateTime(2018, 9, 19, 21, 4, 19, 256, DateTimeKind.Local), HomeContent = "This is the description of an article. Read more.", HomeHeader = "Dummy article" },
                        new { ArticleId = 9, CategoryId = 3, DateCreated = new DateTime(2018, 9, 19, 21, 4, 19, 256, DateTimeKind.Local), HomeContent = "This is the description of an article. Read more.", HomeHeader = "Dummy article" }
                    );
                });

            modelBuilder.Entity("NewsNow.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new { CategoryId = 1, Name = "News" },
                        new { CategoryId = 2, Name = "Sports" },
                        new { CategoryId = 3, Name = "Politics" }
                    );
                });

            modelBuilder.Entity("NewsNow.Models.ExampleStatisticsModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EntersAmount");

                    b.Property<string>("OldestManName");

                    b.HasKey("ID");

                    b.ToTable("ExampleStatistics");
                });

            modelBuilder.Entity("NewsNow.Models.Article", b =>
                {
                    b.HasOne("NewsNow.Models.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
