// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsNow.Models;

namespace NewsNow.Migrations
{
    [DbContext(typeof(NewsNowContext))]
    [Migration("20180919162919_Initiat-Data2")]
    partial class InitiatData2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NewsNow.Models.ArticleModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryID");

                    b.Property<string>("DetailedContent");

                    b.Property<string>("DetailedHeader");

                    b.Property<string>("HomeContent");

                    b.Property<string>("HomeHeader");

                    b.Property<string>("HomeImage");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Articles");

                    b.HasData(
                        new { ID = 1, CategoryID = 1, HomeContent = "A text describing this article", HomeHeader = "Watch: Attack in Syria" }
                    );
                });

            modelBuilder.Entity("NewsNow.Models.CategoryModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new { ID = 1, Name = "Politics" }
                    );
                });

            modelBuilder.Entity("NewsNow.Models.ExampleStatisticsModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EntersAmount");

                    b.Property<string>("OldestManName");

                    b.HasKey("ID");

                    b.ToTable("ExampleStatistics");
                });

            modelBuilder.Entity("NewsNow.Models.ArticleModel", b =>
                {
                    b.HasOne("NewsNow.Models.CategoryModel", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
