// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsNow.Models;

namespace NewsNow.Migrations
{
    [DbContext(typeof(NewsNowContext))]
    [Migration("20180923135825_More categories")]
    partial class Morecategories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NewsNow.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<string>("DetailedContent");

                    b.Property<string>("DetailedHeader");

                    b.Property<string>("HomeContent");

                    b.Property<string>("HomeHeader");

                    b.Property<string>("HomeImage");

                    b.HasKey("ArticleId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new { ArticleId = 1, CategoryId = 1, DateCreated = new DateTime(2018, 9, 23, 16, 58, 25, 66, DateTimeKind.Local), HomeContent = "This is the description of an article. Read more.", HomeHeader = "Targets in Syria: Bombs", HomeImage = "https://i.ytimg.com/vi/R_iYQlMw0r0/maxresdefault.jpg" },
                        new { ArticleId = 2, CategoryId = 1, DateCreated = new DateTime(2018, 9, 23, 16, 58, 25, 68, DateTimeKind.Local), HomeContent = "This is the description of an article. Read more.", HomeHeader = "\"West side is a prison\"", HomeImage = "http://www.bworldonline.com/wp-content/uploads/2018/02/Megaworld-Westside-City.jpg" },
                        new { ArticleId = 3, CategoryId = 1, DateCreated = new DateTime(2018, 9, 23, 16, 58, 25, 68, DateTimeKind.Local), HomeContent = "This is the description of an article. Read more.", HomeHeader = "The Israeli startups in space", HomeImage = "https://3c1703fe8d.site.internapcdn.net/newman/gfx/news/hires/2017/whatisspacet.jpg" },
                        new { ArticleId = 4, CategoryId = 2, DateCreated = new DateTime(2018, 9, 23, 16, 58, 25, 68, DateTimeKind.Local), HomeContent = "This is the description of an article. Read more.", HomeHeader = "1:0 on Raanana vs Kaka", HomeImage = "https://sportshub.cbsistatic.com/i/r/2018/07/15/31f520b7-cad4-48f7-8509-485d51cfb90a/thumbnail/370x208/26c493f4ffe1ad85aea04580c4eb45bb/lionel-messi-argentina.jpg" },
                        new { ArticleId = 5, CategoryId = 2, DateCreated = new DateTime(2018, 9, 23, 16, 58, 25, 68, DateTimeKind.Local), HomeContent = "This is the description of an article. Read more.", HomeHeader = "Dummy article" },
                        new { ArticleId = 6, CategoryId = 2, DateCreated = new DateTime(2018, 9, 23, 16, 58, 25, 68, DateTimeKind.Local), HomeContent = "This is the description of an article. Read more.", HomeHeader = "Dummy article" },
                        new { ArticleId = 7, CategoryId = 3, DateCreated = new DateTime(2018, 9, 23, 16, 58, 25, 68, DateTimeKind.Local), HomeContent = "This is the description of an article. Read more.", HomeHeader = "Dummy article" },
                        new { ArticleId = 8, CategoryId = 3, DateCreated = new DateTime(2018, 9, 23, 16, 58, 25, 68, DateTimeKind.Local), HomeContent = "This is the description of an article. Read more.", HomeHeader = "Dummy article" },
                        new { ArticleId = 9, CategoryId = 3, DateCreated = new DateTime(2018, 9, 23, 16, 58, 25, 68, DateTimeKind.Local), HomeContent = "This is the description of an article. Read more.", HomeHeader = "Dummy article" }
                    );
                });

            modelBuilder.Entity("NewsNow.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new { CategoryId = 1, Name = "World" },
                        new { CategoryId = 2, Name = "Politics" },
                        new { CategoryId = 3, Name = "Buisness" },
                        new { CategoryId = 4, Name = "Sports" },
                        new { CategoryId = 5, Name = "Colture" },
                        new { CategoryId = 6, Name = "Opinions" }
                    );
                });

            modelBuilder.Entity("NewsNow.Models.ExampleStatisticsModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EntersAmount");

                    b.Property<string>("OldestManName");

                    b.HasKey("ID");

                    b.ToTable("ExampleStatistics");
                });

            modelBuilder.Entity("NewsNow.Models.Article", b =>
                {
                    b.HasOne("NewsNow.Models.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
